import { useContext } from 'react'
import AppContext from '../context/AppContext'

import Head from 'next/head'
import { Inter } from 'next/font/google'

import Header from '../app/components/NavBar/Header'
import CreationsGrid from '../app/components/Creations/CreationsGrid'
import CreationSaveModal from '../app/components/CreationSaveModal'

import stylesHeader from '../styles/Header.module.css'
import stylesCreationsGrid from '../styles/CreationsGrid.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Index (): JSX.Element {
  const context = useContext(AppContext)

  const currentCreationModalCreation = context?.currentCreationModalCreation
  const isSaveCreationModalOpen = useContext(AppContext).isSaveCreationModalOpen
  const setIsSaveCreationModalOpen = useContext(AppContext)

	return (
    <>
      <Head>
        <title>Eden Art</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>

      <main className={stylesHeader.headerWrapper}>
        <Header />
      </main>

      <CreationSaveModal
        creation={currentCreationModalCreation}
      />

      <section className={stylesCreationsGrid.creationsWrapper}>
        <CreationsGrid />
      </section>
    </>
    </>
  )
}