// import Head from 'next/head'
// import Link from 'next/link'

// import { Inter } from 'next/font/google'



// const inter = Inter({ subsets: ['latin'] })

// export default function IndexPage() {
//   return (
    // <>
    //   <Head>
    //     <title>Eden Art</title>
    //     <meta name='description' content='Create & Share AI Art' />
    //     <meta name='viewport' content='width=device-width, initial-scale=1' />
    //     <link rel='icon' href='/favicon.ico' />
    //   </Head>

    //   <main className={stylesHeader.headerWrapper}>
    //     <Header />
    //   </main>

    //   <section className={stylesCreationsGrid.creationsWrapper}>
    //     <CreationsGrid />
    //   </section>
    // </>
//   )
// }

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'

import Header from '../app/components/Header'
import CreationsGrid from '../app/components/Creations/CreationsGrid'

import stylesHeader from '../styles/Header.module.css'
import stylesCreationsGrid from '../styles/CreationsGrid.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Index (): JSX.Element {
	return (
    <>
      <Head>
        <title>Eden Art</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>

      <main className={stylesHeader.headerWrapper}>
        <Header />
      </main>

      <section className={stylesCreationsGrid.creationsWrapper}>
        <CreationsGrid />
      </section>
    </>
    </>
  )
}