import React from 'react'
import type { FC } from 'react'
import Head from 'next/head'
import Header from '../components/NavBar/Header'
import styles from '../styles/Home.module.css'

const Profile: FC = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Header />
			</main>
		</>
	)
}

export default Profile
